language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh

script:
- "./_build.sh"

deploy:
  provider: pages
  skip_cleanup: true
  repo: vickyscowcroft/bookdown_lecture_notes_guide
  target-branch: gh-pages
  local-dir: book
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master