# Referencing {#sec:referencing}

## Adding citations {#sec:add-cite}

You can reference publications etc using the following syntax:

```markdown
@bibcode 
```
where `bibcode` is the bibcode for the entry in your bib file (see Sec. \@ref(sec:bib-files)). This will give the equivalent of the LaTeX `\citet{}` command.
Example:
```markdown
@2016Scowcroft showed that the SMC is a very elongated galaxy.
```
@2016Scowcroft showed that the SMC is a very elongated galaxy.

For `\citep{}`, just put the citation in square brackets.

```markdown
The first observations of SMC Cepheids were taken over 100 years ago [@1912Leavitt].
```
The first observations of SMC Cepheids were taken over 100 years ago [@1912Leavitt].

## Bibliography files {#sec:bib-files}

Assuming you're using natbib style references you can pass the same bib file to bookdown. 

Example bib file entry:
```markdown
@ARTICLE{1912Leavitt,
       author = {{Leavitt}, Henrietta S. and {Pickering}, Edward C.},
        title = "{Periods of 25 Variable Stars in the Small Magellanic Cloud.}",
      journal = {Harvard College Observatory Circular},
         year = "1912",
       volume = {173},
        pages = {1},
}
```

## Reference style {#sec:ref-style}

The referencing style is controlled in the `index.Rmd` file. 

At the top of this file you'll find the section that defines things like the book title, output format etc. The following lines are where you define the bib file names and referencing format. You can have multiple bib files.

```markdown
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
```

Any chapter that includes references will have a the reference list at the end. You can also include a separate reference list for the whole document. To make sure this goes right at the end I usually name my file `99-references.Rmd`. It should contain the following text:

```markdown
`r if (knitr::is_html_output()) '# References {-}'`
```
This will create an **un-numbered** section at the end of the book called 'References' that has the full reference list.





